[default]
port = 8000
# workers = [number of cpus * 2]
keep_alive = 5
# secret_key = [randomly generated at launch]
limits = { forms = 32768, json = "1 MiB"  }

[debug]
address = "127.0.0.1"
limits = { json = "10MiB" }

[release]
address = "0.0.0.0"